### ISSUE TITLE
README.md Issue (Critical)

### ISSUE THREAD

**Issue by Egg-Roll** [ReeseHatfield/OpenPOS#1]
Selecting the _License_ link in the **Table of Contents** does not take you anywhere. 

Test Steps:

1. Navigate to the **OpenPOS** README.md.
2. Select the _License_ link.
4. Verify the link redirects the user to the _License_ section

**Comment by ReeseHatfield** [comment]
## Issue #1: README.md Issue (Critical)
# Fix: Added license and created readme link
